# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EUmN7lWbGHQQMs-yNHcyViHgjRIFbikd

### Clone repo containing training script
"""

# Commented out IPython magic to ensure Python compatibility.
! git clone https://github.com/mmarouen/Road-Lane-Semantic-segmentation.git
# %cd Road-Lane-Semantic-segmentation/

"""### Run training script"""

import os
os.environ['PYTHONPATH'] += ":/content/Road-Lane-Semantic-segmentation"
!chmod 755 load_from_gdrive.sh

!python roadseg/scripts/train_chain.py -c configs.json

"""### Save model file and training performance plots to gdrive"""

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
target_file = "/content/gdrive/My Drive/semantic_segmentation/fcn32.h5"

!mkdir -p "/content/gdrive/My Drive/semantic_segmentation/plots"
!cp plots/training_perf.png "/content/gdrive/My Drive/semantic_segmentation/plots/training_perf.png"
!cp models/fcn32.h5 "/content/gdrive/My Drive/semantic_segmentation/fcn32.h5"